---
name: Deploy Cloud Function to GCP

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'main'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.SA_KEY }}'

      - name: Deploy Cloud Function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: pipelines_trigger
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          entry_point: pipelines_trigger
          event_trigger_type: google.storage.object.finalize
          event_trigger_resource: projects/${{ secrets.GCP_PROJECT_ID }}/buckets/${{ secrets.GCP_BUCKET_NAME }}
          timeout: 540s
          runtime: python39
